backend:
  name: github
  repo: vidyutsaikia/NexgendigitalHub
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: pages
    label: Pages
    files:
      - file: "src/pages/about.md"
        label: "About Page"
        name: about
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
