backend:
  name: github
  repo: vidyutsaikia/NexgendigitalHub
  branch: main
  auth_type: implicit
  app_id: y4TkKo0hoPDr6gcbS8YdWRYady95HjmW
  auth_endpoint: https://dev-i4h2n4mlis6yhmkx.us.auth0.com
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pdfs"
    label: "PDFs"
    folder: "static/uploads/pdfs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }