backend:
  name: github
  repo: vidyutsaikia/NexgendigitalHub
  branch: main
  auth_type: implicit
  app_id: ${AUTH0_CLIENT_ID}
  auth_endpoint: ${AUTH0_ISSUER_BASE_URL}/authorize

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pdfs"
    label: "PDFs"
    folder: "static/uploads/pdfs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }