backend:
  name: github
  repo: vidyutsaikia/NexgendigitalHub
  branch: main

media_folder: "static/uploads" # Where files get stored in repo
public_folder: "/uploads"      # Public URL for those files

collections:
  - name: "pdfs"
    label: "PDFs"
    folder: "static/uploads/pdfs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file", media_library: true }